# Generated by Django 4.2.4 on 2023-08-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_auther', models.CharField(max_length=100)),
                ('post_slug', models.CharField(max_length=100)),
                ('post_body', models.CharField(max_length=1000)),
                ('post_publish_date', models.DateTimeField(verbose_name='date published')),
                ('post_create_date', models.DateTimeField(verbose_name='date created')),
                ('post_update_date', models.DateTimeField(verbose_name='date updated')),
                ('post_status', models.CharField(max_length=100)),
            ],
        ),
    ]
