# Generated by Django 4.2.4 on 2023-08-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_rename_post_auther_post_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_body',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], max_length=100),
        ),
    ]
