# Generated by Django 4.2.4 on 2023-08-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_remove_post_post_body_alter_post_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_body',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
